development:
    dialect: postgres
    datasource: postgres://postgres:postgres@localhost:5432/development?sslmode=disable
    dir: db/migrations
    table: migrations

production:
    dialect: postgres
    datasource: ${DATABASE_URL}
    dir: db/migrations
    table: migrations