FROM heroku/heroku:18-build as build

COPY . /app
WORKDIR /app

# Build Go
RUN mkdir -p /tmp/go/buildpack /tmp/go/build_cache /tmp/go/env
RUN curl https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/go.tgz | tar xz -C /tmp/go/buildpack
RUN STACK=heroku-18 /tmp/go/buildpack/bin/compile /app /tmp/go/build_cache /tmp/go/env

# Build npm for asset compile using webpack
RUN mkdir -p /tmp/nodejs/buildpack /tmp/nodejs/build_cache /tmp/nodejs/env
RUN curl https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz | tar xz -C /tmp/nodejs/buildpack
RUN STACK=heroku-18 /tmp/nodejs/buildpack/bin/compile /app /tmp/nodejs/build_cache /tmp/nodejs/env

# Prepare final, minimal image
FROM heroku/heroku:18

COPY --from=build /app /app
ENV HOME /app
WORKDIR /app
RUN useradd -m heroku
# Change login shell from sh to bash, because .profile.d/*.sh generated by nodejs buildpack expects to be run at bash.
RUN usermod -s /bin/bash heroku
USER heroku
#ENTRYPOINT /bin/bash -c